-- Migration number: 0007
-- Tujuan:
-- - Bypass sementara bug Cloudflare D1 remote migration wrapper (code: 7500 / FK failure)
--   saat rebuild parent table `users` via wrangler migration transaction.
-- - Menjaga pipeline migration tetap hijau (no-op) sambil eksekusi perubahan schema users
--   dilakukan manual via D1 Console sesuai runbook operasional.
--
-- Caller:
-- - wrangler d1 migrations apply --remote (CI/CD)
--
-- Dependensi:
-- - Eksekusi manual SQL di D1 Console wajib sudah/akan dilakukan terpisah.
--
-- Side effects:
-- - Histori migration 0007 bersifat no-op (operational drift terdokumentasi di RUNBOOK.md
--   dan optimalisasi_plan.md).

-- no-op by design