export type MediaCategory = "general" | "artikel" | "profil" | "galeri";
export type MediaStatus = "active" | "pending_delete" | "deleted" | "delete_failed";
export type MediaRow = { id:number; file_url:string; storage_key:string; thumb_storage_key:string|null; kategori_penggunaan:MediaCategory; alt_text:string|null; mime_type:"image/webp"|"image/jpeg"|"image/png"; size_bytes:number; width:number|null; height:number|null; uploaded_by:number; created_at:string; status:MediaStatus };
const columns = "id, file_url, storage_key, thumb_storage_key, kategori_penggunaan, alt_text, mime_type, size_bytes, width, height, uploaded_by, created_at, status";
export const insertMedia = (db:D1Database,p:{file_url:string;storage_key:string;thumb_storage_key:string;kategori_penggunaan:MediaCategory;alt_text:string|null;mime_type:"image/webp"|"image/jpeg"|"image/png";size_bytes:number;width:number|null;height:number|null;uploaded_by:number}) => db.prepare(`INSERT INTO dokumentasi (file_url,storage_key,thumb_storage_key,kategori_penggunaan,alt_text,mime_type,size_bytes,width,height,uploaded_by) VALUES (?,?,?,?,?,?,?,?,?,?) RETURNING ${columns}`).bind(p.file_url,p.storage_key,p.thumb_storage_key,p.kategori_penggunaan,p.alt_text,p.mime_type,p.size_bytes,p.width,p.height,p.uploaded_by).first<MediaRow>();
export const getMediaById = (db:D1Database,id:number) => db.prepare(`SELECT ${columns} FROM dokumentasi WHERE id = ? AND status = 'active'`).bind(id).first<MediaRow>();
export const countMedia = (db:D1Database,category?:MediaCategory|null) => category ? db.prepare("SELECT COUNT(*) as total FROM dokumentasi WHERE status = 'active' AND kategori_penggunaan = ?").bind(category).first<{total:number|string}>() : db.prepare("SELECT COUNT(*) as total FROM dokumentasi WHERE status = 'active'").first<{total:number|string}>();
export const listMedia = (db:D1Database,p:{limit:number;offset:number},category?:MediaCategory|null) => category ? db.prepare(`SELECT ${columns} FROM dokumentasi WHERE status = 'active' AND kategori_penggunaan = ? ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(category,p.limit,p.offset).all<MediaRow>() : db.prepare(`SELECT ${columns} FROM dokumentasi WHERE status = 'active' ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(p.limit,p.offset).all<MediaRow>();
export const countMediaReferences = (db:D1Database,id:number) => db.prepare("SELECT COUNT(*) AS total FROM media_references WHERE media_id = ?").bind(id).first<{total:number|string}>();
export const enqueueMediaDeletion = (db:D1Database,row:MediaRow,keys:string[]) => db.batch([
  db.prepare("UPDATE dokumentasi SET status = 'pending_delete', deletion_requested_at = CURRENT_TIMESTAMP, deletion_error = NULL WHERE id = ? AND status = 'active' AND NOT EXISTS (SELECT 1 FROM media_references WHERE media_id = ?)").bind(row.id, row.id),
  ...keys.map(key=>db.prepare("INSERT INTO media_deletion_outbox (media_id, storage_key) SELECT ?, ? WHERE changes() = 1 ON CONFLICT(media_id, storage_key) DO NOTHING").bind(row.id,key)),
]);
export const updateMediaMetadataById = (db:D1Database,id:number,u:{alt_text?:string|null;kategori_penggunaan?:MediaCategory}) => { const sets:string[]=[]; const binds:(string|number|null)[]=[]; if(Object.prototype.hasOwnProperty.call(u,"alt_text")){sets.push("alt_text = ?");binds.push(u.alt_text??null)} if(Object.prototype.hasOwnProperty.call(u,"kategori_penggunaan")){sets.push("kategori_penggunaan = ?");binds.push(u.kategori_penggunaan??null)} binds.push(id); return db.prepare(`UPDATE dokumentasi SET ${sets.join(", ")} WHERE id = ? AND status = 'active' RETURNING ${columns}`).bind(...binds).first<MediaRow>(); };
